const mongoose=require('mongoose');
const jobSchema=new mongoose.Schema({
    CompanyName:{
        type:String,
        required:true,
    },
    Title:{
        type:String,
        required:true,
    },
    Description:{
        type:String,
        required:true,
    },
    LogoUrl:{
        type:String,
        required:true,
    },
    Salary:{
        type:String,
        required:true,
    },
    Location:{
        type:String,
        required:true,
    },
    Duration:{
        type:String,
        required:true,
    },
    LocationType:{
        type:String,
        required:true,
    },
},
    {timestamps:{createdAt:"createdAt",updatedAt:"updatedAt"}},
)
module.exports=mongoose.model("job",jobSchema);